version: 2

models:
  - name: stg_my_first_model
    description: "Staging model for first dataset"
    columns:
      - name: id
        description: "Primary key"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "Model built on top of staging"
    columns:
      - name: id
        description: "Primary key"
        data_tests:
          - unique
          - not_null

  - name: stg_customers
    description: "Staging view built from the customers seed"
    columns:
      - name: customer_id
        description: "Primary key from seed"
        data_tests:
          - not_null
          - unique

      - name: status
        description: "Customer status"
        data_tests:
          - accepted_values:
              arguments:
                values: ["active", "inactive"]
