version: 2

models:
  - name: stg_my_first_model
    description: "Staging model for first dataset"
    columns:
      - name: id
        description: "Primary key"
        data_tests:
          - unique
          - not_null

  - name: stg_customers
    description: "Staging view built from the customers seed"
    columns:
      - name: customer_id
        description: "Primary key from seed"
        data_tests:
          - not_null
          - unique

      - name: status
        description: "Customer status"
        data_tests:
          - accepted_values:
              arguments:
                values: ["active", "inactive"]

  - name: stg_orders
    description: "Staging view built from the orders seed (typed + cleaned)."
    columns:
      - name: order_id
        description: "Order primary key."
        data_tests:
          - not_null
          - unique

      - name: customer_id
        description: "FK to customer (dim_customers)."
        data_tests:
          - not_null

      - name: order_date
        description: "Order date (YYYY-MM-DD)."
        data_tests:
          - not_null

      - name: amount
        description: "Order total amount."
        data_tests:
          - not_null

      - name: status
        description: "Order payment lifecycle status."
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["paid", "cancelled", "refunded"]
